live_config_reload = true

[window]
decorations = "none"
padding = { x = 7, y = 7 }

[font]
normal = { family = "LiberationMono", style = "Regular" }
bold = { family = "LiberationMono", style = "Bold" }
bold_italic = { family = "LiberationMono", style = "BoldItalic" }
size = 7

[colors]
primary = { foreground = "#DEB887", background = "#161616" }
cursor = { cursor = "#ED5AB3" }
vi_mode_cursor = { cursor = "#ED5AB3" }
draw_bold_text_with_bright_colors = true
[colors.normal]
black = '#1c1f24'
red = '#ff6c6b'
green = '#98be65'
yellow = '#da8548'
blue = '#51afef'
magenta = '#c678dd'
cyan = '#5699af'
white = '#202328'
[colors.bright]
black = '#5b6268'
red = '#da8548'
green = '#4db5bd'
yellow = '#ecbe7b'
blue = '#3071db'
magenta = '#a9a1e1'
cyan = '#46d9ff'
white = '#dfdfdf'

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
