#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

HOSTNAME="rnoba"
TIMEZONE="America/Sao_Paulo"
LOCALE="en_US.UTF-8"
KEYMAP="us"
TARGET_DISK="/dev/nvme0n1"
EFI_SIZE="512M"
VOID_REPO="https://repo-default.voidlinux.org/current"
ARCH="x86_64"

EFI_UUID=""
ROOT_UUID=""

PACKAGES=(
    grub grub-x86_64-efi efibootmgr dosfstools
    NetworkManager network-manager-applet
		dbus elogind
    pipewire pulseaudio
    p7zip unzip
    alacritty zsh tmux i3 dmenu firefox mpv neovim flameshot
    base-devel gcc clang git curl direnv
    noto-fonts-ttf noto-fonts-cjk noto-fonts-emoji nerd-fonts
    vulkan-loader ripgrep xclip
    xorg xorg-server
)

log_info()  { printf "%b[INFO]%b %s\n"  "$GREEN" "$NC" "$1"; }
log_warn()  { printf "%b[WARN]%b %s\n"  "$YELLOW" "$NC" "$1"; }
log_error() { printf "%b[ERROR]%b %s\n" "$RED"   "$NC" "$1"; exit 1; }

check_root() { [[ $EUID -eq 0 ]] || log_error "Run as root"; }
check_uefi() { [[ -d /sys/firmware/efi ]] || log_error "UEFI mode required"; }

get_part() {
    local disk="$1" num="$2"
    if [[ $disk =~ nvme || $disk =~ mmcblk ]]; then echo "${disk}p${num}"; else echo "${disk}${num}"; fi
}

confirm_disk() {
    log_warn "This will WIPE ALL DATA on $TARGET_DISK !"
    lsblk -f "$TARGET_DISK"
    echo
    read -p "Type 'YES' to continue: " confirm
    [[ "$confirm" == "YES" ]] || log_error "Cancelled"
}

partition_disk() {
    log_info "Partitioning $TARGET_DISK..."
    wipefs -af "$TARGET_DISK"
    parted -s "$TARGET_DISK" mklabel gpt
    parted -s "$TARGET_DISK" mkpart primary fat32 1MiB "$EFI_SIZE"
    parted -s "$TARGET_DISK" set 1 esp on
    parted -s "$TARGET_DISK" mkpart primary ext4 "$EFI_SIZE" 100%
    sleep 2
    partprobe "$TARGET_DISK" || true
    sleep 2
    log_info "Partitioning done"
}

format_partitions() {
    local efi_part=$(get_part "$TARGET_DISK" 1)
    local root_part=$(get_part "$TARGET_DISK" 2)
    log_info "Formatting..."
    mkfs.vfat -F32 "$efi_part"
    mkfs.ext4 -F "$root_part"
    EFI_UUID=$(blkid -s UUID -o value "$efi_part")
    ROOT_UUID=$(blkid -s UUID -o value "$root_part")
    log_info "Formatted (EFI UUID: $EFI_UUID | Root UUID: $ROOT_UUID)"
}

mount_partitions() {
    local efi_part=$(get_part "$TARGET_DISK" 1)
    local root_part=$(get_part "$TARGET_DISK" 2)
    log_info "Mounting..."
    mount "$root_part" /mnt
    mkdir -p /mnt/boot/efi
    mount "$efi_part" /mnt/boot/efi
    log_info "Mounted"
}

generate_fstab() {
    log_info "Generating /etc/fstab..."
    cat > /mnt/etc/fstab <<EOF
# /etc/fstab - generated by installer
UUID=$ROOT_UUID /               ext4    defaults        0 1
UUID=$EFI_UUID  /boot/efi       vfat    defaults        0 2
EOF
    log_info "fstab generated"
}

install_base_system() {
    log_info "Bootstrapping base-system..."
    export XBPS_ARCH="$ARCH"

    mkdir -p /mnt/var/db/xbps/keys
    cp /var/db/xbps/keys/* /mnt/var/db/xbps/keys/ 2>/dev/null || true

    xbps-install -Sy -r /mnt -R "$VOID_REPO" base-system
    log_info "base-system installed"
}

update_xbps_and_system() {
    log_info "Updating xbps and full system in target..."
    xbps-install -r /mnt -Su xbps               # Update package manager first
    xbps-install -r /mnt -Su                    # Full system update
    log_info "Target system updated"
}

install_additional_packages() {
    log_info "Installing extra packages..."
    xbps-install -Sy -r /mnt -R "$VOID_REPO" "${PACKAGES[@]}"
    log_info "Extra packages installed"
}

configure_system() {
    log_info "Basic configuration..."

    echo "$HOSTNAME" > /mnt/etc/hostname

    cat > /mnt/etc/hosts <<EOF
127.0.0.1   localhost
::1         localhost
127.0.1.1   $HOSTNAME.localdomain $HOSTNAME
EOF

    echo "$LOCALE UTF-8" > /mnt/etc/default/libc-locales
    echo "en_US.UTF-8 UTF-8" >> /mnt/etc/default/libc-locales  # ensure at least one
    echo "LANG=$LOCALE" > /mnt/etc/locale.conf

    ln -sf "/usr/share/zoneinfo/$TIMEZONE" /mnt/etc/localtime

    echo "KEYMAP=$KEYMAP" > /mnt/etc/rc.conf

    log_info "Configuration done"
}

configure_dracut() {
    log_info "Configuring dracut (hostonly)..."
    mkdir -p /mnt/etc/dracut.conf.d
    cat > /mnt/etc/dracut.conf.d/10-hostonly.conf <<EOF
hostonly=yes
hostonly_cmdline=yes
EOF
}

setup_chroot() {
    log_info "Setting up chroot mounts..."
    mount -t proc     none     /mnt/proc
    mount -t sysfs    none     /mnt/sys
    mount -o bind     /dev     /mnt/dev
    mount -t devpts   none     /mnt/dev/pts
    cp -L /etc/resolv.conf /mnt/etc/
    log_info "Chroot ready"
}

chroot_and_finalize() {
    log_info "Running commands inside chroot..."
    chroot /mnt /bin/bash <<'EOF'
        # Generate locales
        xbps-reconfigure -f glibc-locales

        # Reconfigure everything (initramfs, etc.)
        xbps-reconfigure -fa
EOF
    log_info "Chroot finalize done"
}

install_bootloader() {
    log_info "Installing GRUB (UEFI)..."
    chroot /mnt /bin/bash <<EOF
        grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=void --recheck
        # If efivarfs issues: try --no-nvram or mount -t efivarfs none /sys/firmware/efi/efivars first
        grub-mkconfig -o /boot/grub/grub.cfg
EOF
    log_info "Bootloader installed"
}

enable_services() {
    log_info "Enabling essential services..."
    for svc in NetworkManager dbus elogind; do
        ln -sfn /etc/sv/"$svc" /mnt/etc/runit/runsvdir/default/
    done
    log_info "Services enabled"
}

configure_zram() {
    log_info "Setting up zram (50% RAM)..."
    cat > /mnt/etc/rc.local <<'EOF'
#!/bin/sh
modprobe zram
echo zstd > /sys/block/zram0/comp_algorithm
echo $(awk '/MemTotal/ {printf "%.0f", $2 * 0.5 * 1024}' /proc/meminfo) > /sys/block/zram0/disksize
mkswap /dev/zram0
swapon /dev/zram0 -p 100
EOF
    chmod +x /mnt/etc/rc.local
    log_info "zram configured"
}

set_root_password() {
    log_info "Setting root password..."
    chroot /mnt passwd root
}

cleanup() {
    log_info "Cleaning up mounts..."
    umount -l /mnt/dev/pts 2>/dev/null || true
    umount -l /mnt/dev     2>/dev/null || true
    umount -l /mnt/sys     2>/dev/null || true
    umount -l /mnt/proc    2>/dev/null || true
    umount -R /mnt/boot/efi 2>/dev/null || true
    umount -R /mnt         2>/dev/null || true
    log_info "Cleanup finished"
}

show_summary() {
    echo
    log_info "Installation Summary"
    echo "──────────────────────"
    echo "Disk:          $TARGET_DISK"
    echo "EFI part:      $(get_part "$TARGET_DISK" 1)  UUID=$EFI_UUID"
    echo "Root part:     $(get_part "$TARGET_DISK" 2)  UUID=$ROOT_UUID"
    echo "Hostname:      $HOSTNAME"
    echo "Timezone:      $TIMEZONE"
    echo "Locale:        $LOCALE"
    echo "Keymap:        $KEYMAP"
    echo
}

main() {
    log_info "Void Linux one-shot installer starting..."

    check_root
    check_uefi
    confirm_disk
    partition_disk
    format_partitions
    mount_partitions
    generate_fstab
    install_base_system
    update_xbps_and_system
    install_additional_packages
    configure_system
    configure_dracut
    enable_services
    configure_zram
    setup_chroot
    chroot_and_finalize
    set_root_password
    install_bootloader
    cleanup
    show_summary

    log_info "Installation finished!"
    echo "Reboot recommendation:"
    echo "  → Reboot now? (y/N)"
    read -r ans
    [[ "$ans" =~ ^[Yy]$ ]] && reboot
}

main "$@"
