colorscheme gruvbox
let g:gruvbox_contrast_dark = 'hard'
set background=dark
syntax on
let g:mapleader=","
set termguicolors
set tabstop=4
set shiftwidth=4

set runtimepath=/home/rnoba/.vim,/home/rnoba/.config/vim,/usr/share/vim/vimfiles,/usr/share/vim/vim91,/usr/share/vim/vimfiles/after,/home/rnoba/.config/vim/after,/usr/bin/fzf
set viminfo+='1000,n~/.config/vim/viminfo
set fillchars=vert:\|,fold:-,eob:\ ,lastline:\@

set nu
set autoindent 
set noswapfile

set relativenumber
set mouse=a

set undodir=$HOME/.config/vim/undo
set undofile

set undolevels=10000
set undoreload=10000000
set incsearch
set scrolloff=8
set clipboard=unnamed

filetype plugin on
filetype indent on

vnoremap <silent> <Leader>Y "+y
nnoremap <silent> <Leader>n :cnext<CR>
nnoremap <silent> <Leader>sf :FZF<CR>
nnoremap <silent> <Leader>p :cprev<CR>
nnoremap <silent> <Leader>s :copen<CR>
nnoremap <silent> <Leader>cc :cclose<CR>

set laststatus=2 
set statusline=%y\ %F\ \%M\ %R\ \%q\ %=Line:\ %l\ Column:\ %v\ (Char:\ (%B'%b')\ Byte\ Offset:\ %o)
set statusline+=%{gutentags#statusline()}

let g:fzf_action = {
			\ 'ctrl-t': 'tab split',
			\ 'ctrl-x': 'split',
			\ 'ctrl-v': 'vsplit'}

let g:fzf_layout = { 'down': '40%' }
let g:fzf_history_dir = '~/.local/share/fzf-history'

hi StatusLine guifg=#1c1f24 guibg=#F1F1F1
hi VertSplit term=reverse ctermfg=16 ctermbg=44 guifg=#1c1f24 guibg=#1c1f24
hi Search term=reverse ctermbg=11 guibg=#18181B
hi CurSearch term=reverse ctermbg=11 guibg=#18181B
hi Visual term=reverse ctermbg=7 guibg=#252528
hi CursorLineSign term=reverse ctermbg=7 guibg=#252528
hi CursorLineFold term=reverse ctermbg=7 guibg=#252528
hi CursorLine term=reverse cterm=bold ctermbg=7 guibg=#252528
hi LineNr term=bold ctermfg=50 guifg=#4F4F4F
hi Type term=underline ctermfg=2 gui=bold guifg=#c678dd
hi Pmenu ctermbg=7 guibg=#252528
