#!/usr/bin/env bash

log_info "Running post-install hook..."

configure_xorg_nvidia() {
	log_info "Configuring custom Xorg settings for NVIDIA..."
	
	if [[ ! -f /mnt/etc/modprobe.d/nvidia.conf ]]; then
		log_warn "NVIDIA not detected, skipping Xorg configuration"
		return
	fi
	
	cat > /mnt/etc/X11/xorg.conf <<'EOF'
# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 580.126.09
#
# ⚠️  IMPORTANT: Customize this for YOUR hardware!
# 
# To generate this file for your system:
# 1. Boot into your new system
# 2. Run: sudo nvidia-xconfig
# 3. Or run: sudo nvidia-settings
# 4. Save configuration and copy it here

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    # HorizSync source: edid, VertRefresh source: edid
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "AOC 24G4"              # ⚠️  CHANGE THIS TO YOUR MONITOR MODEL
    HorizSync       200.0 - 200.0          # ⚠️  ADJUST FOR YOUR MONITOR
    VertRefresh     48.0 - 180.0           # ⚠️  ADJUST FOR YOUR MONITOR
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "NVIDIA GeForce RTX 3060"  # ⚠️  CHANGE THIS TO YOUR GPU
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth   24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DP-0"     # ⚠️  CHANGE TO YOUR DISPLAY PORT
    Option         "metamodes" "1920x1080_180 +0+0"    # ⚠️  CHANGE RESOLUTION AND REFRESH RATE
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    SubSection     "Display"
		Depth					 24
    EndSubSection
EndSection
EOF
	
	log_info "Custom Xorg configuration applied"
	log_warn "Remember to customize /etc/X11/xorg.conf for your hardware!"
}

configure_firefox_policies() {
	log_info "Applying custom Firefox policies..."
	
	if ! chroot_exec "command -v firefox" &>/dev/null; then
		log_warn "Firefox not installed, skipping configuration"
		return
	fi
	
	mkdir -p /mnt/etc/firefox/policies
	cat > /mnt/etc/firefox/policies/policies.json <<'EOF'
{
	"policies": {
		"SearchEngines": {
			"Default": "DuckDuckGo",
			"Remove": ["Google", "Bing", "Amazon.com", "eBay"]
		},
		"Extensions": {
			"Install": [
				"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
				"https://addons.mozilla.org/firefox/downloads/latest/bitwarden-password-manager/latest.xpi",
				"https://addons.mozilla.org/firefox/downloads/latest/multi-account-containers/latest.xpi"
			]
		},
		"DisableTelemetry": true,
		"DisablePocket": true,
		"OfferToSaveLogins": false,
		"PromptForDownloadLocation": true,
		"Preferences": {
			"browser.startup.homepage": {
				"Value": "about:blank",
				"Status": "default"
			}
		},
		"FirefoxHome": {
			"Search": true,
			"TopSites": false,
			"SponsoredTopSites": false,
			"Highlights": false,
			"Pocket": false,
			"SponsoredPocket": false,
			"Snippets": false
		}
	}
}
EOF
	
	log_info "Firefox policies configured"
}

configure_custom_dns() {
	log_info "Configuring custom DNS servers..."
	
	cat > /mnt/etc/resolv.conf <<'EOF'
# Custom DNS Configuration
# Cloudflare DNS (fast, privacy-focused)
nameserver 1.1.1.1
nameserver 1.0.0.1

# Google DNS (backup)
nameserver 8.8.8.8
nameserver 8.8.4.4

# Quad9 DNS (security-focused alternative)
# nameserver 9.9.9.9
# nameserver 149.112.112.112
EOF
	
	log_info "Custom DNS configured"
}

configure_system_tweaks() {
	log_info "Applying system tweaks and optimizations..."
	
	mkdir -p /mnt/etc/sysctl.d
	cat > /mnt/etc/sysctl.d/99-custom.conf <<'EOF'
# Custom sysctl settings

# Increase file watchers for development
fs.inotify.max_user_watches=524288

# TCP fast open for better network performance
net.ipv4.tcp_fastopen=3

# Increase network buffer sizes
net.core.rmem_max=16777216
net.core.wmem_max=16777216
EOF
	
# cat > /mnt/etc/profile.d/custom.sh <<'EOF'
# EOF
	
	log_info "System tweaks applied"
}

configure_xorg_nvidia
configure_firefox_policies
configure_custom_dns
# configure_system_tweaks

log_info "Post-install hook completed"
echo
